# Generated by Django 4.1.5 on 2023-04-19 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200, null=True)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Reistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_date', models.DateField(null=True)),
                ('hackathon_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Base.hackathon')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Base.user')),
            ],
        ),
    ]
