# Generated by Django 4.1.5 on 2023-04-19 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0002_user_reistration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_name', models.CharField(max_length=400)),
                ('hackathon_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Base.hackathon')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Base.user')),
            ],
        ),
    ]
