# Generated by Django 4.1.5 on 2023-04-20 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0004_submission_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackathon',
            name='Hackathon_image',
            field=models.ImageField(blank=True, null=True, upload_to='background_img/', verbose_name='background image'),
        ),
        migrations.AddField(
            model_name='hackathon',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='background_img/', verbose_name='background image'),
        ),
        migrations.AddField(
            model_name='hackathon',
            name='type_os_sub',
            field=models.CharField(choices=[('Image', 'Image'), ('File', 'File'), ('Link', 'Link')], default='Text', max_length=10),
        ),
    ]
