# Generated by Django 4.1.5 on 2023-04-20 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0005_hackathon_hackathon_image_hackathon_background_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.AddField(
            model_name='user',
            name='Username',
            field=models.CharField(default='##', max_length=200, unique=True),
        ),
    ]
