# Generated by Django 4.1.5 on 2023-04-20 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0006_remove_user_email_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='LINK of your submission',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='Submission_image',
            field=models.ImageField(blank=True, null=True, upload_to='submission/', verbose_name='submission image'),
        ),
    ]
