# Generated by Django 4.1.5 on 2023-04-20 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0007_submission_link of your submission_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='LINK of your submission',
            new_name='submission_link',
        ),
    ]
