# Generated by Django 4.1.5 on 2023-04-20 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0008_rename_link of your submission_submission_submission_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='submission_link',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
